import { useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Index() {
  const url = "https://calendly.com/hello-world-school"
  const router = useRouter()

  useEffect(() => {
    router.push(url)
  })

  return (
    <div className={styles.container}>
    <Head>
      <title>Hello World School</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to Hello World!
      </h1>

      <p className={styles.description}>
        You will be redirected in just a second
      </p>

    </main>
  </div>
)
}
